spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/xe
    username: near_sky
    password: 1q2w3e4r
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 40MB

  profiles:
    include: jwt

resource:
  image: 'file:\\\D:\Src\git\near-sky\hiking-api\images\'
